# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SpeakToMe' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'AFNetworking', '~> 3.0'
  # Pods for SpeakToMe

  target 'SpeakToMeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SpeakToMeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
